#!/usr/bin/env bash
#
# run command at a specified time

if test -z "$1"; then
    echo 'usage : [time] [command]'
    exit 1
fi

{
    until [[ $(printf '%(%R)T') == "$1" ]]; do
        sleep 10
    done

    "${@:2}"
} &
