#!/usr/bin/env bash
#
# run command at a specified time

time=$1
task=${*:2}

if test -z "$time"; then
    echo 'usage : [time] [command]'
    exit 1
fi

{
    until [[ $(printf '%(%R)T') == "$time" ]]; do
        read -rst 10 -N 1000
    done

    $task
} &
