#!/bin/sh
#
# convert to gif

dir=/tmp/frames
pal=/tmp/palette.png

mkdir -p "$dir"

# generate frames
ffmpeg -loglevel error -i "$1" -r 15 "$dir/%06d.png"

# generate palette
ffmpeg -loglevel error -i "$dir/%06d.png" -vf palettegen -y "$pal"

# generate gif
ffmpeg -loglevel error -i "$dir/%06d.png" -i "$pal" -lavfi paletteuse -y output.gif

rm -rf "$dir" "$pal"
