#!/usr/bin/env bash
#
# get orphans

read -ra dependencies <<< $(prt-get quickdep "$1")

for package in "${dependencies[@]}"; do
    while read -r dependent; do
        [[ ${dependencies[*]} =~ $dependent ]] || continue 2
    done < <(prt-get dependent --recursive "$package")

    echo "$package"
done
