#!/usr/bin/env bash
#
# get orphans

read -ra dependencies <<< $(prt-get quickdep "$1")

for package in "${dependencies[@]}"; do
    var=1

    while read -r dependent; do
        [[ ${dependencies[*]} =~ $dependent ]] || { var=0; break; }
    done < <(prt-get dependent --recursive "$package")

    ((var)) && echo "$package"
done
