#!/usr/bin/env bash
#
# rename pictures based on exifs

_()
{
    var=$(exif -mt DateTime "$1") || exit 1

    # format date
    ext=${1##*.}
    var=${var//:/-}
    var=${var// /_}.$ext

    mv   "$1"  "$var"
    echo "$1 -> $var"
}

if ((! $#)); then
    echo 'usage : pics [file...]'
    exit 1
fi

for file in "$@"; { _ "$file"; }
