#!/usr/bin/env bash
#
# rename pictures based on exifs

while [[ $# -gt 0 ]]; do
    var=$(exif -m -t DateTime "$1")

    # exit if var is empty
    test "$var" || exit 1

    # format datas
    ext=${1##*.}
    var=${var//:/-}
    var=${var// /_}

    mv "$1" "$var.$ext"

    shift
done
