#!/usr/bin/env bash
#
# rename pictures based on exifs

_()
{
    var=$(exif -mt DateTime "$1")

    # exit if there is no date
    test "$var" || exit 1

    # format date
    ext=${1##*.}
    var=${var//:/-}
    var=${var// /_}

    mv   "$1"  "$var.$ext"
    echo "$1 -> $var.$ext"
}

if ((! $#)); then
    echo 'usage : pics [file...]'
    exit 1
fi

for file in "$@"; { _ "$file"; }
