#!/usr/bin/env bash
#
# center text

clear

# get lines and columns
shopt -s checkwinsize; (:;:)

while read -r a; do
    ((nb++))
done < "$1"

# center vertically
for ((; i++ < (LINES - nb) / 2;)) do
    echo
done

# center horizontally
while read -r a; do
    printf "%*s\\n" "$(((${#a} + COLUMNS) / 2))" "$a"
done < "$1"
