#!/usr/bin/env bash
#
# center text

# \e[2J   : clear the screen
# \e[H    : print in 0, 0
# \e[?25l : hide the cursor
printf '\e[2J\e[H\e[?25l'

shopt -s checkwinsize; (:;:)

# center vertically
mapfile nb < "$1"
for ((; i++ < (LINES - ${#nb[@]}) / 2;)) do
    echo
done

# center horizontally
while read -r a; do
    printf '%*s\n' $(((${#a} + COLUMNS) / 2)) "$a"
done < "$1"

# \e[?25h : show the cursor
trap 'printf "\e[?25h"' INT EXIT

# keep the prompt busy
sleep 10
