#!/bin/sh
#
# record with ffmpeg

dir=~/pics/records
var=$(date +%F_%H-%M-%S)

x=$(bspc query -T -m | jq .rectangle.width)
y=$(bspc query -T -m | jq .rectangle.height)

mkdir -p "$dir" || exit 1

ffmpeg -loglevel 16 \
    -s "${x}x${y}" \
    -r 30 \
    -f x11grab \
    -i :0.0 \
    "$dir/$var.mp4"
