#!/bin/sh
#
# record with ffmpeg

dir=~/imgs/records
cur=$(date +%F_%H-%M-%S)

mkdir -p "$dir" || exit 1

# get monitor resolution
wattr wh "$(lsw -r)" | {
    read -r w h

    ffmpeg -loglevel 16 \
        -s "${w}x${h}"  \
        -f x11grab      \
        -i :0.0         \
        -r 30           \
        -preset slow    \
        -c:v h264       \
        -crf 20         \
        "$dir/$cur.mp4"
}
