#!/bin/sh
#
# record with ffmpeg

dir=~/pics/records
cur=$(date +%F_%H-%M-%S)

mkdir -p "$dir" || exit 1

# get monitor resolution
wattr wh "$(lsw -r)" |
{
    read -r w h

    ffmpeg -loglevel error \
        -s "${w}x${h}" \
        -r 30 \
        -f x11grab \
        -i :0.0 \
        "$dir/$cur.mp4"
}
