#!/bin/sh
#
# mount my sdcard

mnt=/mnt/sdcard
dev=/dev/mmcblk0p1

_ ()
    if [ ! -e "$1" ]; then
        echo "error : '$1' not found"
        exit 1
    fi

_ "$mnt"
_ "$dev"

sudo mount "$dev" "$mnt"
