#!/usr/bin/env bash
#
# pretty mpc status

# colors
a=$'\e[93m'
t=$'\e[00m'

_ () mpc current -f "%$1%"

cat << EOF

${a}Album${t}:     $(_ album)
${a}Artist${t}:    $(_ artist)
${a}Title${t}:     $(_ title)

EOF
