#!/usr/bin/env bash
#
# pretty mpc status

_ () { mpc current -f "%$1%"; }

# colors
a=$'\e[93m'
t=$'\e[00m'

cat << EOF

${a}Album${t}:     $(_ album)
${a}Artist${t}:    $(_ artist)
${a}Title${t}:     $(_ title)

EOF
