#!/bin/sh
#
# /etc/NetworkManager/dispatcher.d/ssid

file=/tmp/ssid

case $2 in
    up)
        # send current SSID
        echo "$CONNECTION_ID" >> $file
	;;
    down)
        # send empty SSID
        echo >> $file
esac
