#!/usr/bin/env bash
#
# simple timer

if [[ ! $2 ]]; then
    echo 'usage : [time] [message]'
    exit 1
fi

{
    until [[ $(printf '%(%H:%M)T') == $1 ]]; do
        sleep 1
    done

    notify-send "$2"
} &
