#!/usr/bin/env bash
#
# simple timer

if test -z "$1"; then
    echo 'usage : [time] [text]'
    exit 1
fi

{
    until [[ $(printf '%(%R)T') == "$1" ]]; do
        sleep 10
    done

    notify-send "${@:2}"
} &
