#!/usr/bin/env bash
#
# todo script

# files
todo=~/.todo
temp=/tmp/todo

cpt=1

add ()
{
    while read -r line; do
        echo "$((cpt++)) -> $line"
    done < $todo
}

del ()
{
    > $temp || exit 1

    while read -r line; do
        (($1 != cpt++)) && echo "$line" >> $temp
    done < $todo

    mv "$temp" "$todo"
}

case $1 in
    add)
        echo "$2" >> $todo
        ;;
    del)
        rp "$2"
        ;;
    *)
        nb
esac
